name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run a multi-line script
    - run: |
        make build
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
