name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os-image: [ubuntu-latest, windows-latest]
    runs-on: ${matrix.os-image}
    steps:
      - uses: actions/checkout@v2
      - run: |
          make
